name: client_it
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizzle_lints: ^1.0.10
  injectable: ^2.1.2
  get_it: ^7.6.0
  injectable_generator: ^2.1.6
  dio: ^4.0.6
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  
  # Сохранение стэйта
  # TODO заменить на flutter_secure_storage 
  hydrated_bloc: ^8.1.0
  # Получает путь к файловой системе
  path_provider: ^2.0.11

dev_dependencies:
  json_serializable: ^6.5.1
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
